#!/bin/bash
python3 -m compileall -b $PYFILE
result = magic_calculation(2, 3)
print(result)
>>> dis.dis(myfunc)
3           0 LOAD_CONST               1 (98)
            3 LOAD_FAST                0 (a)
            6 LOAD_FAST                1 (b)
            9 BINARY_POWER
           10 BINARY_ADD
           11 RETURN_VALUE
